docs: update lib version and SDK require
for lib:
1.3.1 -> 1.3.3

for SDK:
go.uber.org\multierr@v1.11.0\error.go:209:20: undefined: atomic.Bool
note: module requires Go 1.19